### ISSUE TITLE
Plugin doesn't work creating shipments with Magento API

### ISSUE THREAD

**Issue by salgua** [YotpoLtd/magento2-module-yotpo-reviews#121]
Hi,
since I'm using [shippypro](https://www.shippypro.com/) to automatically create shipments, the plugin stops to send orders to Yotpto. Shippypro doesn't install any module in Magento, simply it create shipments using standard Magento 2 API. It seems that your module doesn't work with shipments created in this way. It works only with shipments created through web admin interface. Could you fix this issue?

#### Yotpo module version 2.4.3

**Comment by salgua** [comment]
I think your event "sales_order_save_after" is not fired using web api.

**Comment by wabakok** [comment]
Hi,

Thanks and apologies for the delays here.  Basically we set up an observer to listen to the order state change.  Orders that are created in complete state directly via API will not trigger our listener, as the order state hasn't actually changed.

If you can create shippypro orders under a different status and set up an automation on your end that changes the order state to complete in Magento it should do the trick.

https://support.yotpo.com/en/article/magento-2-installing-yotpo#customizing-order-status-sent-to-yotpo

**Comment by salgua** [comment]
Hi, thank you for your response.
Could you explain better which kind of automation you means? 
Something like a module with an observer to listen orders and change status?
Thank you!
