### ISSUE TITLE
Column layout specified in .xml files overriding base themes.

### ISSUE THREAD

**Issue by chrBrd** [YotpoLtd/magento2-module-yotpo-reviews#123]
Upgrading this module from 2.4 to 2.4.3 broke our site's layout. Our theme is built off the Magento base theme (which uses `2columns-left` for category layout) and we hadn't explicitly specified a `layout` attribute in the theme's `page` element. The new `catalog_product_view.xml` etc.layouts included with this module _do_ have a `layout` attribute specified, and it overrode our theme.

While it's served as a good indicator that we should explicitly declare page layouts in our theme to prevent this happening in future, the layout files in this module should not declare anything beyond the bare minimum required for them to work; all those `layout="1column"` entries should possibly be removed.

**Comment by wabakok** [comment]
Hi,

Sorry for the delays on this one.  Our R&D team is reviewing the PR.

**Comment by webamondo** [comment]
I'm hoping this is what has caused my site to loose the layered navigation sidebar and instead inserts it at the bottom of the page, I have narrowed it down to yotpo but not found the exact cause yet

**Comment by chrBrd** [comment]
@webamondo Quite probably, the specified layout breaking our layered navigation is what led me to open this issue and submit a PR for it.

**Comment by chrBrd** [comment]
@wabakok 

Any update on this? It's now been over three weeks for your 'R&D team' to review a change that should have taken no more than 10 minutes (and shoudln't have been made in the first place).

I may have fixed this temporarily on our server, but as @webamondo shows this will affect your other customers.

**Comment by webamondo** [comment]
I really need this fixing too, I've currently hacked it in vendor for two customers which is less than ideal

**Comment by chrBrd** [comment]
@webamondo In the interim, a more ideal fix is to explicitly declare the desired `layout` attribute in the theme's `page` element so you aren't modifying `vendor` code. Should also prevent the same problem happening further down the line if any other dependencies do something similar.

That said, this shouldn't have been an issue in the first place, and it certainly shouldn't be taking this long to implement their own fix, or review mine, even accounting for it being over the festive season.

**Comment by chrBrd** [comment]
Many thanks @DanGlz!
