### ISSUE TITLE
Javascript Error on Category Page Star Click

### ISSUE THREAD

**Issue by friendscottn** [YotpoLtd/magento2-module-yotpo-reviews#151]
To Reproduce:
- Enable the bottom line on category pages
- Have some reviews
- Click the stars on a category page

Expected Bahavior:
- User navigates to the product page reviews area

Actual Behavior:
- A javascript error occurs: 
```
    Uncaught TypeError: Cannot read property 'get' of undefined
    at Function.e.scrollToReviewsTabInMainWidget (widget.js:1)
    at HTMLDivElement.<anonymous> (widget.js:9)
```

Example:
https://demo.banyanbotanicals.com/men/tops-men.html

Screenshot:
![image](https://user-images.githubusercontent.com/2660768/56839322-ca1e0b00-6836-11e9-9e6b-f732996c9183.png)

**Comment by wabakok** [comment]
Hi,

Thanks for bringing this up.  
Basically, bottomlines behave one way on a product page and another way on a category page.  It looks like in your case category page bottomlines behave like they are on a product page.  

Can you please open up a support case for this one?
https://support.yotpo.com/en/article/submitting-a-support-ticket

Please reply with the case number so I can update our support guys.

Thanks!
