### ISSUE TITLE
Duplicated CSS

### ISSUE THREAD

**Issue by hobadams** [YotpoLtd/magento2-module-yotpo-reviews#158]
All of the {less} added in the file `yotpo/module-review/view/frontend/web/css/source/_module.less` is added to both `styles-m.css` and `styles-l.css`

By wrapping your code in the following it will only appear in `styles-m.css`, preventing it from being difficult to override + bloating the css.

```
& when (@media-common = true) {
YOUR LESS HERE
}
```

It would be great to see this added to your module.

Thanks

**Comment by wabakok** [comment]
Hi,

Thanks for pointing this out!
I've notified our devs and they are currently reviewing your suggestion.

**Comment by hobadams** [comment]
@wabakok - Thanks :-)

**Comment by wabakok** [comment]
@hobadams 
Appreciate your patience here.  We've added your suggestion to our latest version, 2.8.1 which is already live :)

**Comment by hobadams** [comment]
Thanks,

This is great news!

I'll update the module on the build I'm working on now :-)

Hob Adams
Senior Developer
[image: Gene Commerce - specialist ecommerce agency]
<http://gene.co.uk/> [image:
Magento Solutions Partner] [image: Magento 2 Solutions Partner]
<https://magento.com/>
T: +44(0) 1273 030390 | 20 Middle Street, Brighton, BN1 1AL
[image: Twitter Logo] <https://twitter.com/gene_commerce> [image: LinkedIn
Logo] <https://www.linkedin.com/company/gene-commerce>
gene.co.uk
Registered Office: 20 Middle Street, Brighton, BN1 1AL. Registered in
England and Wales No.08589522

**Comment by hobadams** [comment]
@wabakok - I'll mark this one as resolved :-)
