### ISSUE TITLE
Bug when compiling Magento to production mode

### ISSUE THREAD

**Issue by ghost** [YotpoLtd/magento2-module-yotpo-reviews#18]
When compiling magento the following error appears. For this reason it is unable to set the store to production mode:

php -d set_time_limit=3600 bin/magento setup:di:compile-multi-tenant

`

```
Errors during compilation:
        Yotpo\Yotpo\Model\Config\Backend\ValidateSettings
                Incorrect dependency in class Yotpo\Yotpo\Model\Config\Backend\ValidateSettings in /home/telefoon/domains/blueburst.nl/public_html/app/code/Yotpo/Yotpo/Model/Config/Backend/ValidateSettings.php
\Psr\Log\LoggerInterface already exists in context object
        Yotpo\Yotpo\Block\Yotpo
                Incorrect dependency in class Yotpo\Yotpo\Block\Yotpo in /home/telefoon/domains/blueburst.nl/public_html/app/code/Yotpo/Yotpo/Block/Yotpo.php
\Magento\Framework\UrlInterface already exists in context object
\Psr\Log\LoggerInterface already exists in context object
        Yotpo\Yotpo\Block\Adminhtml\System\Config\Form\YotpoButton
                Incorrect dependency in class Yotpo\Yotpo\Block\Adminhtml\System\Config\Form\YotpoButton in /home/telefoon/domains/blueburst.nl/public_html/app/code/Yotpo/Yotpo/Block/Adminhtml/System/Config/Form/YotpoButton.php
\Magento\Store\Model\StoreManagerInterface already exists in context object
\Psr\Log\LoggerInterface already exists in context object
        Yotpo\Yotpo\Controller\Adminhtml\YotpoController\YotpoController
                Incompatible argument type: Required type: \Magento\Backend\App\Action\Context. Actual type: \Magento\Framework\App\Action\Context; File:
/home/telefoon/domains/blueburst.nl/public_html/app/code/Yotpo/Yotpo/Controller/Adminhtml/YotpoController/YotpoController.php

        Yotpo\Yotpo\Helper\Data
                Incorrect dependency in class Yotpo\Yotpo\Helper\Data in /home/telefoon/domains/blueburst.nl/public_html/app/code/Yotpo/Yotpo/Helper/Data.php
\Psr\Log\LoggerInterface already exists in context object
Total Errors Count: 5
```

`

Please let me know if you have a solution for this problem or a module update.

**Comment by Bobstar040** [comment]
Is there any fix for this? Yotpo is gone after setting production mode. I use M 2.1.8.

**Comment by shrinet** [comment]
I am also getting error on enabling production mode. After enable production mode Yotpo is gone and producing error 
![yotpo-error](https://user-images.githubusercontent.com/2738619/34612851-7e72f140-f251-11e7-96c2-ed3e93f5a7c1.PNG)

Please suggest

**Comment by billykov** [comment]
Hey @shrinet What version of the Yotpo Module are you using?

**Comment by shrinet** [comment]
Hello @billykov thanks for reply, I am using here is details of composer-lock.
`"name": "yotpo/module-review",
            "version": "2.2.7",
            "source": {
                "type": "git",
                "url": "https://github.com/YotpoLtd/magento2-plugin.git",
                "reference": "0de43039dfefdfd00df01ffb26a805a2137c5de6"
            },`

Please let me know if any more information required.

**Comment by sa3iedsabbah** [comment]
Hey @shrinet can you tell me witch Magento2.x and PHP version you are using?

**Comment by shrinet** [comment]
@sa3iedsabbah I am using PHP7.1 FPM and Magento2.1.7

**Comment by sa3iedsabbah** [comment]
@shrinet We are going to support PHP7.1 in the near future(still having some tests to do), but for sure, magento2.1.x DON'T support PHP7.1
I recommend you so switch to PHP7.0.X ( notice that PHP7.0.3-5, had some issues).

source, magento docs
http://devdocs.magento.com/guides/v2.1/install-gde/system-requirements-tech.html 
and 
https://magento.stackexchange.com/questions/116418/why-doesnt-magento-2-1-support-php-7-0-3-to-7-0-5

**Comment by shrinet** [comment]
Thanks for making it clear. I will adjust it. Thanks a lot

**Comment by alex-histev** [comment]
@shrinet Is switching to PHP7.0 solved your issue?

I have Magento 2.2.2 with  PHP7.1 FPM and I have exactly the same bug in production mode.

It works if switch off HTML-minifying in admin area before deploying to production mode. 

@sa3iedsabbah could you advise me how to solve issue with HTML-minifying? Which part of module may be a reason of it?

**Comment by shrinet** [comment]
@alex-histev I fixed issue by downgrading PHP. I dont think HTML minify have any issue now, I am using it.

**Comment by alex-histev** [comment]
Hi @shrinet, thank you for your answer. I've tested module with downgraded PHP but it doesn't work for me. Issue appear in production mode only. For now I use production mode without HTML minification and it works.

**Comment by kamilszewczyk** [comment]
This seems to be the same issue I've found and it's the same issue I've reported on Magento Core: https://github.com/magento/magento2/issues/18048
It seems like minification is breaking stuff and this ticket has give me useful information about version of PHP that might cause the issues.

I have found that changing `<?php echo` to <?=` fixes the issue with minification so this might be a workaround.
