### ISSUE TITLE
IE 11 Support

### ISSUE THREAD

**Issue by hobadams** [YotpoLtd/magento2-module-yotpo-reviews#181]
Hey guys,

I'm trying to use a Yotpo Gallery on my site.

On IE11 I'm getting the following error in your `widget.js` file:

`Object does not support property or method 'forEach' - widget.js (5,29347)`.

The path is https://staticw2.yotpo.com/fEJjethhubYIKhBEz3InUXkOp5jFYR2emtO1zn7X/widget.js

Any help would be appreciated.

**Comment by yotpaul** [comment]
> Hey guys,
> 
> I'm trying to use a Yotpo Gallery on my site.
> 
> On IE11 I'm getting the following error in your `widget.js` file:
> 
> `Object does not support property or method 'forEach' - widget.js (5,29347)`.
> 
> The path is https://staticw2.yotpo.com/fEJjethhubYIKhBEz3InUXkOp5jFYR2emtO1zn7X/widget.js
> 
> Any help would be appreciated.

Hey! It seems like IE indeed does not support `forEach`. Let me check about this and get back to you.

**Comment by yotpaul** [comment]
A bug has been open about this internally.

**Comment by brightonmike** [comment]
@yotpaul if your issue is on a Nodelist you can either polyfill forEach

```
if (window.NodeList && !NodeList.prototype.forEach) {
    NodeList.prototype.forEach = Array.prototype.forEach;
}
```

or use array from

```
var widgets = Array.from(document.querySelectorAll(selector));
widgets.forEach....
```

**Comment by hobadams** [comment]
@yotpaul - thanks. Do you have any idea of timescales for this one?

**Comment by yotpaul** [comment]
@hobadams @brightonmike It's currently being taken care of by R&D.
Code deployment should be this week.
I'll update as soon as it's done.

Thanks!

**Comment by yotpaul** [comment]
Fix has been deployed. Please update your widget version to apply.
Please note that `widget.js` may be cached so changes will not be immediately visible.
You can switch to _Immediate Update (Temporary)_ in order to see the change and force the cache refresh.

**Comment by hobadams** [comment]
@yotpaul - lovely thank you! ! appreciate you and your team getting this fixed :-)

**Comment by hobadams** [comment]
@yotpaul - Any news on the question above? Thanks

**Comment by yotpaul** [comment]
@hobadams The widget version is updated through your Yotpo dashboard by going to https://yap.yotpo.com/#/tools/widget/general_settings
Unless I misunderstood what you've meant?
