### ISSUE TITLE
yotpo_rich_snippets table average_score only allowed to save as integer 

### ISSUE THREAD

**Issue by t2zhhe00** [YotpoLtd/magento2-module-yotpo-reviews#207]
Hello,

We encounter the issue average_score is not matched in Yotpo API. The problem is even score return from API is a float number eg 4.3, when it save to database it is become 4. 

The solution is change the Lenght of average_score data from `10,0` to `10,2`

BR
Heng

**Comment by yotpaul** [comment]
Thanks for the report @t2zhhe00 I'll open up a task for this internally.

**Comment by yotpaul** [comment]
@t2zhhe00 a bug has been opened about this, thanks again for reporting!

**Comment by yotpaul** [comment]
Will be addressed by #219

**Comment by yotpaul** [comment]
Correction, addressed by https://github.com/YotpoLtd/magento2-module-yotpo-reviews/pull/221
