### ISSUE TITLE
My module version says 3.0.0, but the latest release is 2.9.2

### ISSUE THREAD

**Issue by shilpambb** [YotpoLtd/magento2-module-yotpo-reviews#215]
Hello team yotpo. I don't know how or why or when it happened, but the composer.json file in the yotpo module is saying version 3.0.0. I'm pasting the composer.json here. I'm wondering if something is wrong and if anyone can tell me what I need to do.

{
    "name": "yotpo/magento2-module-yotpo-reviews",
    "description": "Yotpo Reviews extension for Magento2",
    "version": "3.0.0",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "require": {
        "php": "~7.1.3||~7.2.0||~7.3.0",
        "magento/framework": "102.0.*",
        "magento/module-backend": "101.0.*",
        "magento/module-catalog": "103.0.*",
        "magento/module-checkout": "100.3.*",
        "magento/module-config": "101.1.*",
        "magento/module-grouped-product": "100.3.*",
        "magento/module-reports": "100.3.*",
        "magento/module-review": "100.3.*",
        "magento/module-sales": "102.0.*",
        "magento/module-store": "101.0.*"
    },
    "replace": {
        "yotpo/module-review": "*",
        "yotpo/module-yotpo": "*"
    },
    "type": "magento2-module",
    "autoload": {
        "files": [
            "cli_commands.php",
            "registration.php"
        ],
        "psr-4": {
            "Yotpo\\Yotpo\\": ""
        }
    }
}

**Comment by yotpaul** [comment]
Hey @shilpambb **2.9.2** is indeed the latest *standalone* release of the Yotpo module.
**3.0.0** is the version that comes bundled with Magento 2.3.3 and above.

**Comment by shilpambb** [comment]
@yotpaul which version does 3.0.0 line up with on this github repository? I imagine the github repository will release faster than Magento. How can we stay up to date with this repository instead of the Magento one?
