### ISSUE TITLE
Which version does 3.0.0 line up with on this github repository and how to stay up to date?

### ISSUE THREAD

**Issue by shilpambb** [YotpoLtd/magento2-module-yotpo-reviews#216]
Which version does 3.0.0 line up with on this github repository? I imagine the github repository will release faster than Magento. How can we stay up to date with this repository instead of the Magento one?

**Comment by shilpambb** [comment]
This is a follow up question from https://github.com/YotpoLtd/magento2-module-yotpo-reviews/issues/215.

**Comment by yotpaul** [comment]
Hey @shilpambb 3.0.0 would be around the same age as version 2.9.0.
I am currently working with R&D to try and get a way to temporarily uninstall the built-in version from Magento.
However, keep in mind that the 2.9.X branch is temporary and is only for older versions of Magento until those are no longer supported by Magento themselves, so if possible I'd advise against moving to the 2.9.X branch if you can hold out till the next module update of the CBE (core bundled extension).
In general, the release cycle according to Magento is every three months. This interval is dictated by them.

**Comment by shilpambb** [comment]
Hi @yotpaul, we also use Braintree through the Gene module. It has a way of replacing the built in Magento version. They do this so that their release cycle is not tied to Magento's release cycle. However, they don't contribute to the Magento module I don't think. Rather, they put out their own with more features. Here is their repo: https://github.com/genecommerce/module-braintree-magento2

I think they do it with the "replace" in their composer.json. Maybe Yotpo can do something similar so we don't have to wait on Magento's release.

**Comment by yotpaul** [comment]
Hey @shilpambb Yotpo's current standing with Magento is a bit more peculiar so we kind of have to adhere to Magento's release cycle.
From my own tests it seems a bit more complicated than just using replace with Composer.
I'm gonna have to see if I can get a somewhat proper solution here.

**Comment by shilpambb** [comment]
Thanks @yotpaul. I haven't looked into a solution, so I'm sure there is more involved, but it would be nice to be able to get updates and bug fixes faster than the Magento release cycle. Thanks for looking into a solution.

**Comment by yotpaul** [comment]
Hey @shilpambb from what I've been able to gather, there are two ways that you can go by to replace the CBE module with a version of your choosing:
1. Open the extension folder that is located under "Vendor" and replace the files there with the files of the desired version from Github manually.
2. Delete the extension from the Vendor folder and install it using this guide: https://github.com/YotpoLtd/magento2-module-yotpo-reviews#install-manually-under-appcode

**Comment by shilpambb** [comment]
I think we'll stick with the Magento release in that case. We were hoping for a more automated solution through composer. If we need any fix urgently, we'll probably use a composer patch file.
