### ISSUE TITLE
Broken reference: the 'yotpo_bottomline' tries to reorder itself towards

### ISSUE THREAD

**Issue by hafizjee** [YotpoLtd/magento2-module-yotpo-reviews#217]
main.INFO: Broken reference: the 'yotpo_bottomline' tries to reorder itself towards 'product.info.addto', but their parents are different: 'product.info.main' and 'product.info.social' respectively. [] []
main.INFO: Broken reference: the 'skip_gallery_before' tries to reorder itself towards 'product.info.media.image', but their parents are different: 'skip_gallery_before.wrapper' and 'product.info.media' respectively. [] []
main.INFO: Broken reference: the 'skip_gallery_after' tries to reorder itself towards 'product.info.media.image', but their parents are different: 'skip_gallery_after.wrapper' and 'product.info.media' respectively. [] []
main.INFO: Broken reference: the 'shopperapproved.product' tries to reorder itself towards 'product.info.detail', but their parents are different: 'product.info.main' and '' respectively. [] []

M going to add customs module for add shopper approved star rating on the detail page but facing this issue how can I resolve this?

**Comment by yotpaul** [comment]
Hey @hafizjee let me check about this and get back to you.

**Comment by yotpaul** [comment]
Internal issue open, will update on resolution.

**Comment by yotpaul** [comment]
Hey @hafizjee,
This is a very common error and is considered a "log spam". It has no effect on functionality.

Are you having troubles using Yotpo or is this just a general concern?

**Comment by hafizjee** [comment]
Hi @yotpaul 
Thanks to the response, yeah you are right "It has no effect on functionality".
