### ISSUE TITLE
How do I uninstall this shit?

### ISSUE THREAD

**Issue by Zyles** [YotpoLtd/magento2-module-yotpo-reviews#220]
Bloating up my 2.3.3 installation.

```
$ composer remove yotpo/module-review
yotpo/module-review is not required in your composer.json and has not been removed

$ php bin/magento module:uninstall -r Yotpo_Yotpo

$ cat app/etc/config.php
'Yotpo_Yotpo' => 1
```

How do I get rid of this? Malware is easier to uninstall.

**Comment by AurelienLavorel** [comment]
Add that on your composer.json
```
    "replace": {
        "yotpo/magento2-module-yotpo-reviews": "*",
        "yotpo/magento2-module-yotpo-reviews-bundle": "*"
    },
```

**Comment by yotpaul** [comment]
@Zyles as the Yotpo module is a CBE (Core Bundled Extension) i.e. comes bundled with any Magento version above 2.3.3, please contact Magento themselves if you've got an issue.

**Comment by Zyles** [comment]
I already did: https://github.com/magento/magento2/issues/26187

And got no help.

When you are responsible for filling up M2 with bloatware. Then you will also take responsibility for support and removal of it.

**Comment by perfpcs** [comment]
@Zyles  here here! totally agree! So tired of Magento trying to decide what I need for tax software (Vertex), Fraud (Signify), reviews (Yotpo) and that clusterf@#$ useless bloatware Temando Shipping. Can Magento just stop with this nonsense?? No one wants this crap and every release of Magento gets worse and worse because they try to decide for us what we as merchants need in our shopping cart. I'm sick of it and I'm sure why more and more of the market is going away from Magento and on towards Shopify. This endless bloat of crap 3rd party over-priced services has got to end!

**Comment by perfpcs** [comment]
And the stupidity continues trying to uninstall this malbloat:
	"replace": {
	"yotpo/magento2-module-yotpo-reviews": "*",
        "yotpo/magento2-module-yotpo-reviews-bundle": "*"
		}

  Problem 1
    - magento/project-community-edition 2.3.3 requires magento/product-community-edition 2.3.3 -> satisfiable by magento/product-community-edition[2.3.3] but these conflict with your requirements or minimum-stability.
    - remove magento/project-community-edition 2.3.3|remove yotpo/magento2-module-yotpo-reviews-bundle-edge 3.0.1
    - don't install yotpo/magento2-module-yotpo-reviews-bundle-edge 3.0.1|remove magento/project-community-edition 2.3.3
    - don't install yotpo/magento2-module-yotpo-reviews-bundle-edge 3.0.1|remove magento/project-community-edition 2.3.3
    - don't install yotpo/magento2-module-yotpo-reviews-bundle-edge 3.0.0|remove magento/project-community-edition 2.3.3
    - Installation request for magento/project-community-edition 2.3.3 -> satisfiable by magento/project-community-edition[2.3.3].
    - Installation request for yotpo/magento2-module-yotpo-reviews-bundle-edge ^3.0 -> satisfiable by yotpo/magento2-module-yotpo-reviews-bundle-edge[3.0.1, 3.0.0].

Anyone else know how to rid this virus?

**Comment by paul-gene** [comment]
@yotpaul pretty sure the module developer is still responsible for maintaining the codebase...
