### ISSUE TITLE
About API version

### ISSUE THREAD

**Issue by hryksbt** [YotpoLtd/magento2-module-yotpo-reviews#292]
Hello,

I believe this repository is a development repository for a module that works with Yotpo's review function listed on the Magento marketplace.
In the Latest stable version of the module connecting Magento and Yotpo, which API version is V1 or V3 on the Yotpo side?

This is not an Issue report, but it would be helpful to get an answer.

Thank you in advance.

**Comment by LiorGingi** [comment]
Hi @hryksbt,

This module is using our [core API V1](https://core-api.yotpo.com/v1.0/reference/welcome#).
We're currently working on a new module that will use [V3](https://core-api.yotpo.com/reference/welcome#) and also add a whole set of new features to the Magento <> Yotpo integration. The new module will be released soon.

Thanks,
Lior Gingihashvili.

**Comment by hryksbt** [comment]
Hello,
Thanks for your reply.
I got that is using V1 now.
I wish that will release near future.
Good luck.
