### ISSUE TITLE
Category: can't find yotpo block

### ISSUE THREAD

**Issue by ccoffee** [YotpoLtd/magento2-module-yotpo-reviews#42]
Adding the bottomline helper callout on a category page does not work.

` <?php $this->helper('Yotpo\Yotpo\Helper\Data')->showBottomline($this, $_product); ?>`

 I believe this is because the xml in the module that creates the bottomline block only targets a block that is available on the product page, not the category page.

```
       <referenceContainer name="product.info.main">
            <block  class="Yotpo\Yotpo\Block\Yotpo" name="bottomline" as="other" template="bottomline.phtml" before="product.info.addto"/>
        </referenceContainer>
```

product.info.main is not on category page, so calling showBottomline won't work, because the "bottomline" block is not added to the category page.

**Comment by billykov** [comment]
Hi @ccoffee, thanks for bringing this up.
Let me check that and get back to you.

**Comment by ccoffee** [comment]
Been a little over two weeks so just checking back. I have tried making a few modifications myself, but it appears in most themes that categories and product lists do not use an individual block for each product, so it cannot target one. It seems it may need a different type of handler for product lists.

**Comment by billykov** [comment]
@ccoffee Hi,
We are working on adding a fix for this, we are trying to find a workaround for it to work on all category pages. It won't be a part of the next release, but hopefully on the one after it.

**Comment by ccoffee** [comment]
Thanks for the update. 

Is there any reason not to inject elements onto the page for each product block with a javascript CMS widget?

```
<div class="yotpo bottomLine"
	data-product-id="{{product_id}}"
	data-url="{{product_url}}">
</div>
```

**Comment by billykov** [comment]
@ccoffee You can give it a try, but I am not sure the parameters ({{product_id}}) will be populated this way

**Comment by ccoffee** [comment]
@billykov understood, these were entered this way just for example sake. (For instance, part of a handlebars/mustache/other template method that can just insert this div into the DOM)

**Comment by billykov** [comment]
@ccoffee. yes if you can add handlebars/mustache/other dynamic params via the javascript CMS - it should work
